// Generated by gencpp from file robot/Goal.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGE_GOAL_H
#define ROBOT_MESSAGE_GOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot
{
template <class ContainerAllocator>
struct Goal_
{
  typedef Goal_<ContainerAllocator> Type;

  Goal_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , address()
    , taskId(0)
    , binId(0)  {
    }
  Goal_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , address(_alloc)
    , taskId(0)
    , binId(0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _address_type;
  _address_type address;

   typedef uint32_t _taskId_type;
  _taskId_type taskId;

   typedef uint32_t _binId_type;
  _binId_type binId;





  typedef boost::shared_ptr< ::robot::Goal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot::Goal_<ContainerAllocator> const> ConstPtr;

}; // struct Goal_

typedef ::robot::Goal_<std::allocator<void> > Goal;

typedef boost::shared_ptr< ::robot::Goal > GoalPtr;
typedef boost::shared_ptr< ::robot::Goal const> GoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot::Goal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot::Goal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot::Goal_<ContainerAllocator1> & lhs, const ::robot::Goal_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.address == rhs.address &&
    lhs.taskId == rhs.taskId &&
    lhs.binId == rhs.binId;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot::Goal_<ContainerAllocator1> & lhs, const ::robot::Goal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot::Goal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::Goal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot::Goal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot::Goal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::Goal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::Goal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot::Goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4870beac0f8c447426c89ad9a47b4d3b";
  }

  static const char* value(const ::robot::Goal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4870beac0f8c4474ULL;
  static const uint64_t static_value2 = 0x26c89ad9a47b4d3bULL;
};

template<class ContainerAllocator>
struct DataType< ::robot::Goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot/Goal";
  }

  static const char* value(const ::robot::Goal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot::Goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
"string address\n"
"uint32 taskId\n"
"uint32 binId\n"
;
  }

  static const char* value(const ::robot::Goal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot::Goal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.address);
      stream.next(m.taskId);
      stream.next(m.binId);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Goal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot::Goal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot::Goal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "address: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.address);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "taskId: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.taskId);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "binId: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.binId);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MESSAGE_GOAL_H
