// Generated by gencpp from file robot/State.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGE_STATE_H
#define ROBOT_MESSAGE_STATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace robot
{
template <class ContainerAllocator>
struct State_
{
  typedef State_<ContainerAllocator> Type;

  State_()
    : position()
    , taskStatus()  {
    }
  State_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , taskStatus(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _taskStatus_type;
  _taskStatus_type taskStatus;





  typedef boost::shared_ptr< ::robot::State_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot::State_<ContainerAllocator> const> ConstPtr;

}; // struct State_

typedef ::robot::State_<std::allocator<void> > State;

typedef boost::shared_ptr< ::robot::State > StatePtr;
typedef boost::shared_ptr< ::robot::State const> StateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot::State_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot::State_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot::State_<ContainerAllocator1> & lhs, const ::robot::State_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.taskStatus == rhs.taskStatus;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot::State_<ContainerAllocator1> & lhs, const ::robot::State_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot::State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot::State_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot::State_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::State_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::State_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5c770faa938bccc8c5b6ab129729e91";
  }

  static const char* value(const ::robot::State_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5c770faa938bcccULL;
  static const uint64_t static_value2 = 0x8c5b6ab129729e91ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot/State";
  }

  static const char* value(const ::robot::State_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point position\n"
"string taskStatus\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::robot::State_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot::State_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.taskStatus);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct State_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot::State_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot::State_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "taskStatus: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.taskStatus);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MESSAGE_STATE_H
