// Generated by gencpp from file robot/LocalizationInfo.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGE_LOCALIZATIONINFO_H
#define ROBOT_MESSAGE_LOCALIZATIONINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot
{
template <class ContainerAllocator>
struct LocalizationInfo_
{
  typedef LocalizationInfo_<ContainerAllocator> Type;

  LocalizationInfo_()
    : x(0.0)
    , y(0.0)
    , heading(0.0)
    , floor_id()
    , user_id()  {
    }
  LocalizationInfo_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , heading(0.0)
    , floor_id(_alloc)
    , user_id(_alloc)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _heading_type;
  _heading_type heading;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _floor_id_type;
  _floor_id_type floor_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _user_id_type;
  _user_id_type user_id;





  typedef boost::shared_ptr< ::robot::LocalizationInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot::LocalizationInfo_<ContainerAllocator> const> ConstPtr;

}; // struct LocalizationInfo_

typedef ::robot::LocalizationInfo_<std::allocator<void> > LocalizationInfo;

typedef boost::shared_ptr< ::robot::LocalizationInfo > LocalizationInfoPtr;
typedef boost::shared_ptr< ::robot::LocalizationInfo const> LocalizationInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot::LocalizationInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot::LocalizationInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot::LocalizationInfo_<ContainerAllocator1> & lhs, const ::robot::LocalizationInfo_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.heading == rhs.heading &&
    lhs.floor_id == rhs.floor_id &&
    lhs.user_id == rhs.user_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot::LocalizationInfo_<ContainerAllocator1> & lhs, const ::robot::LocalizationInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot::LocalizationInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::LocalizationInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot::LocalizationInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot::LocalizationInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::LocalizationInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::LocalizationInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot::LocalizationInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c3fed3fa27ab9dbf5a4834ff70d5a2e";
  }

  static const char* value(const ::robot::LocalizationInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c3fed3fa27ab9dbULL;
  static const uint64_t static_value2 = 0xf5a4834ff70d5a2eULL;
};

template<class ContainerAllocator>
struct DataType< ::robot::LocalizationInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot/LocalizationInfo";
  }

  static const char* value(const ::robot::LocalizationInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot::LocalizationInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 heading\n"
"string floor_id\n"
"string user_id\n"
;
  }

  static const char* value(const ::robot::LocalizationInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot::LocalizationInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.heading);
      stream.next(m.floor_id);
      stream.next(m.user_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocalizationInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot::LocalizationInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot::LocalizationInfo_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "floor_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.floor_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "user_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.user_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MESSAGE_LOCALIZATIONINFO_H
